### ISSUE TITLE
Same UUID because of Lua cache

### ISSUE THREAD

**Issue by ozanmuyes** [thibaultcha/lua-resty-jit-uuid#12]
Hi @thibaultcha, thanks for the awesome library.

In the development environment I turn off the Lua cache via `lua_code_cache off;` directive in the NGINX/OpenResty configuration file. I followed the documentation add the `init_worker_by_lua_block` block and then use the library to generate UUID v4. I am seeding the generator once in the `init_worker_by_lua_block` block but if I call `uuid()` function once (of course `local uuid = require "resty.jit-uuid"`) it returns the same UUID for every time. It doesn't matter if I restart the server or increase `worker_processes` count, the sequence still the same.

Then I realised the Lua code caching is off. Once turned on UUIDs are random. I just wanted to put it here to heads-up for future users (including myself though). At the end of the day we all know one missing semi-colon may be the cause of all hair-pulling.

Greetings.

**Comment by thibaultcha** [comment]
Hi!

I just added a note to the README advising users to be weary of the `lua_code_cache` directive in d6956557fbb004d3a6020a26148f43143a8b4428 to avoid such confusion going forward. Thanks for sharing your experience!
